<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#What-is-NumPy?" data-toc-modified-id="What-is-NumPy?-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>What is NumPy?</a></span><ul class="toc-item"><li><span><a href="#Why-Use-NumPy?" data-toc-modified-id="Why-Use-NumPy?-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>Why Use NumPy?</a></span></li><li><span><a href="#Why-is-NumPy-Faster-Than-Lists?" data-toc-modified-id="Why-is-NumPy-Faster-Than-Lists?-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>Why is NumPy Faster Than Lists?</a></span></li><li><span><a href="#Which-Language-is-NumPy-written-in?" data-toc-modified-id="Which-Language-is-NumPy-written-in?-1.3"><span class="toc-item-num">1.3&nbsp;&nbsp;</span>Which Language is NumPy written in?</a></span></li><li><span><a href="#Import-NumPy" data-toc-modified-id="Import-NumPy-1.4"><span class="toc-item-num">1.4&nbsp;&nbsp;</span>Import NumPy</a></span></li><li><span><a href="#Create-a-NumPy-ndarray-Object" data-toc-modified-id="Create-a-NumPy-ndarray-Object-1.5"><span class="toc-item-num">1.5&nbsp;&nbsp;</span>Create a NumPy ndarray Object</a></span></li><li><span><a href="#Dimensions-in-Arrays" data-toc-modified-id="Dimensions-in-Arrays-1.6"><span class="toc-item-num">1.6&nbsp;&nbsp;</span>Dimensions in Arrays</a></span></li><li><span><a href="#0-D-Arrays" data-toc-modified-id="0-D-Arrays-1.7"><span class="toc-item-num">1.7&nbsp;&nbsp;</span>0-D Arrays</a></span></li><li><span><a href="#Check-Number-of-Dimensions?" data-toc-modified-id="Check-Number-of-Dimensions?-1.8"><span class="toc-item-num">1.8&nbsp;&nbsp;</span>Check Number of Dimensions?</a></span></li><li><span><a href="#Higher-Dimensional-Arrays" data-toc-modified-id="Higher-Dimensional-Arrays-1.9"><span class="toc-item-num">1.9&nbsp;&nbsp;</span>Higher Dimensional Arrays</a></span></li></ul></li><li><span><a href="#Array-Indexing" data-toc-modified-id="Array-Indexing-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Array Indexing</a></span><ul class="toc-item"><li><span><a href="#Access-Array-Elements" data-toc-modified-id="Access-Array-Elements-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>Access Array Elements</a></span></li><li><span><a href="#Access-2-D-Arrays" data-toc-modified-id="Access-2-D-Arrays-2.2"><span class="toc-item-num">2.2&nbsp;&nbsp;</span>Access 2-D Arrays</a></span></li><li><span><a href="#Access-3-D-Arrays" data-toc-modified-id="Access-3-D-Arrays-2.3"><span class="toc-item-num">2.3&nbsp;&nbsp;</span>Access 3-D Arrays</a></span></li><li><span><a href="#Negative-Indexing" data-toc-modified-id="Negative-Indexing-2.4"><span class="toc-item-num">2.4&nbsp;&nbsp;</span>Negative Indexing</a></span></li></ul></li><li><span><a href="#Array-Slicing" data-toc-modified-id="Array-Slicing-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Array Slicing</a></span><ul class="toc-item"><li><span><a href="#Negative-Slicing" data-toc-modified-id="Negative-Slicing-3.1"><span class="toc-item-num">3.1&nbsp;&nbsp;</span>Negative Slicing</a></span></li><li><span><a href="#STEP" data-toc-modified-id="STEP-3.2"><span class="toc-item-num">3.2&nbsp;&nbsp;</span>STEP</a></span></li><li><span><a href="#Slicing-2-D-Arrays" data-toc-modified-id="Slicing-2-D-Arrays-3.3"><span class="toc-item-num">3.3&nbsp;&nbsp;</span>Slicing 2-D Arrays</a></span></li></ul></li><li><span><a href="#Data-Types" data-toc-modified-id="Data-Types-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Data Types</a></span><ul class="toc-item"><li><span><a href="#Checking-the-Data-Type-of-an-Array" data-toc-modified-id="Checking-the-Data-Type-of-an-Array-4.1"><span class="toc-item-num">4.1&nbsp;&nbsp;</span>Checking the Data Type of an Array</a></span></li><li><span><a href="#What-if-a-Value-Can-Not-Be-Converted?" data-toc-modified-id="What-if-a-Value-Can-Not-Be-Converted?-4.2"><span class="toc-item-num">4.2&nbsp;&nbsp;</span>What if a Value Can Not Be Converted?</a></span></li><li><span><a href="#Converting-Data-Type-on-Existing-Arrays" data-toc-modified-id="Converting-Data-Type-on-Existing-Arrays-4.3"><span class="toc-item-num">4.3&nbsp;&nbsp;</span>Converting Data Type on Existing Arrays</a></span></li></ul></li><li><span><a href="#Array-Copy-vs-View" data-toc-modified-id="Array-Copy-vs-View-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Array Copy vs View</a></span><ul class="toc-item"><li><span><a href="#COPY:" data-toc-modified-id="COPY:-5.1"><span class="toc-item-num">5.1&nbsp;&nbsp;</span>COPY:</a></span></li><li><span><a href="#VIEW:" data-toc-modified-id="VIEW:-5.2"><span class="toc-item-num">5.2&nbsp;&nbsp;</span>VIEW:</a></span></li><li><span><a href="#Check-if-Array-Owns-it's-Data" data-toc-modified-id="Check-if-Array-Owns-it's-Data-5.3"><span class="toc-item-num">5.3&nbsp;&nbsp;</span>Check if Array Owns it's Data</a></span></li></ul></li><li><span><a href="#Array-Shape" data-toc-modified-id="Array-Shape-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>Array Shape</a></span><ul class="toc-item"><li><span><a href="#Shape-of-an-Array" data-toc-modified-id="Shape-of-an-Array-6.1"><span class="toc-item-num">6.1&nbsp;&nbsp;</span>Shape of an Array</a></span></li><li><span><a href="#What-does-the-shape-tuple-represent?" data-toc-modified-id="What-does-the-shape-tuple-represent?-6.2"><span class="toc-item-num">6.2&nbsp;&nbsp;</span>What does the shape tuple represent?</a></span></li></ul></li><li><span><a href="#Reshaping-arrays" data-toc-modified-id="Reshaping-arrays-7"><span class="toc-item-num">7&nbsp;&nbsp;</span>Reshaping arrays</a></span><ul class="toc-item"><li><span><a href="#Reshape-From-1-D-to-2-D" data-toc-modified-id="Reshape-From-1-D-to-2-D-7.1"><span class="toc-item-num">7.1&nbsp;&nbsp;</span>Reshape From 1-D to 2-D</a></span></li><li><span><a href="#Reshape-From-1-D-to-3-D" data-toc-modified-id="Reshape-From-1-D-to-3-D-7.2"><span class="toc-item-num">7.2&nbsp;&nbsp;</span>Reshape From 1-D to 3-D</a></span></li><li><span><a href="#Can-We-Reshape-Into-any-Shape?" data-toc-modified-id="Can-We-Reshape-Into-any-Shape?-7.3"><span class="toc-item-num">7.3&nbsp;&nbsp;</span>Can We Reshape Into any Shape?</a></span></li><li><span><a href="#Returns-Copy-or-View?" data-toc-modified-id="Returns-Copy-or-View?-7.4"><span class="toc-item-num">7.4&nbsp;&nbsp;</span>Returns Copy or View?</a></span></li><li><span><a href="#Unknown-Dimension" data-toc-modified-id="Unknown-Dimension-7.5"><span class="toc-item-num">7.5&nbsp;&nbsp;</span>Unknown Dimension</a></span></li><li><span><a href="#Flattening-the-arrays" data-toc-modified-id="Flattening-the-arrays-7.6"><span class="toc-item-num">7.6&nbsp;&nbsp;</span>Flattening the arrays</a></span></li></ul></li><li><span><a href="#Iterating-Arrays" data-toc-modified-id="Iterating-Arrays-8"><span class="toc-item-num">8&nbsp;&nbsp;</span>Iterating Arrays</a></span><ul class="toc-item"><li><span><a href="#Iterating-2-D-Arrays" data-toc-modified-id="Iterating-2-D-Arrays-8.1"><span class="toc-item-num">8.1&nbsp;&nbsp;</span>Iterating 2-D Arrays</a></span></li><li><span><a href="#Iterating-3-D-Arrays" data-toc-modified-id="Iterating-3-D-Arrays-8.2"><span class="toc-item-num">8.2&nbsp;&nbsp;</span>Iterating 3-D Arrays</a></span></li><li><span><a href="#Iterating-Arrays-Using-nditer()" data-toc-modified-id="Iterating-Arrays-Using-nditer()-8.3"><span class="toc-item-num">8.3&nbsp;&nbsp;</span>Iterating Arrays Using nditer()</a></span></li><li><span><a href="#Iterating-Array-With-Different-Data-Types" data-toc-modified-id="Iterating-Array-With-Different-Data-Types-8.4"><span class="toc-item-num">8.4&nbsp;&nbsp;</span>Iterating Array With Different Data Types</a></span></li><li><span><a href="#Iterating-With-Different-Step-Size" data-toc-modified-id="Iterating-With-Different-Step-Size-8.5"><span class="toc-item-num">8.5&nbsp;&nbsp;</span>Iterating With Different Step Size</a></span></li><li><span><a href="#Enumerated-Iteration-Using-ndenumerate()" data-toc-modified-id="Enumerated-Iteration-Using-ndenumerate()-8.6"><span class="toc-item-num">8.6&nbsp;&nbsp;</span>Enumerated Iteration Using ndenumerate()</a></span></li></ul></li><li><span><a href="#Joining-NumPy-Arrays" data-toc-modified-id="Joining-NumPy-Arrays-9"><span class="toc-item-num">9&nbsp;&nbsp;</span>Joining NumPy Arrays</a></span><ul class="toc-item"><li><span><a href="#Joining-Arrays-Using-Stack-Functions" data-toc-modified-id="Joining-Arrays-Using-Stack-Functions-9.1"><span class="toc-item-num">9.1&nbsp;&nbsp;</span>Joining Arrays Using Stack Functions</a></span></li><li><span><a href="#Stacking-Along-Rows" data-toc-modified-id="Stacking-Along-Rows-9.2"><span class="toc-item-num">9.2&nbsp;&nbsp;</span>Stacking Along Rows</a></span></li><li><span><a href="#Stacking-Along-Columns" data-toc-modified-id="Stacking-Along-Columns-9.3"><span class="toc-item-num">9.3&nbsp;&nbsp;</span>Stacking Along Columns</a></span></li><li><span><a href="#Stacking-Along-Height-(depth)" data-toc-modified-id="Stacking-Along-Height-(depth)-9.4"><span class="toc-item-num">9.4&nbsp;&nbsp;</span>Stacking Along Height (depth)</a></span></li></ul></li><li><span><a href="#Splitting-NumPy-Arrays" data-toc-modified-id="Splitting-NumPy-Arrays-10"><span class="toc-item-num">10&nbsp;&nbsp;</span>Splitting NumPy Arrays</a></span><ul class="toc-item"><li><span><a href="#Split-Into-Arrays" data-toc-modified-id="Split-Into-Arrays-10.1"><span class="toc-item-num">10.1&nbsp;&nbsp;</span>Split Into Arrays</a></span></li><li><span><a href="#Splitting-2-D-Arrays" data-toc-modified-id="Splitting-2-D-Arrays-10.2"><span class="toc-item-num">10.2&nbsp;&nbsp;</span>Splitting 2-D Arrays</a></span></li></ul></li><li><span><a href="#Searching-Arrays" data-toc-modified-id="Searching-Arrays-11"><span class="toc-item-num">11&nbsp;&nbsp;</span>Searching Arrays</a></span><ul class="toc-item"><li><span><a href="#Search-Sorted" data-toc-modified-id="Search-Sorted-11.1"><span class="toc-item-num">11.1&nbsp;&nbsp;</span>Search Sorted</a></span></li><li><span><a href="#Search-From-the-Right-Side" data-toc-modified-id="Search-From-the-Right-Side-11.2"><span class="toc-item-num">11.2&nbsp;&nbsp;</span>Search From the Right Side</a></span></li><li><span><a href="#Multiple-Values" data-toc-modified-id="Multiple-Values-11.3"><span class="toc-item-num">11.3&nbsp;&nbsp;</span>Multiple Values</a></span></li></ul></li><li><span><a href="#Sorting-Arrays" data-toc-modified-id="Sorting-Arrays-12"><span class="toc-item-num">12&nbsp;&nbsp;</span>Sorting Arrays</a></span><ul class="toc-item"><li><span><a href="#Sorting-a-2-D-Array" data-toc-modified-id="Sorting-a-2-D-Array-12.1"><span class="toc-item-num">12.1&nbsp;&nbsp;</span>Sorting a 2-D Array</a></span></li></ul></li><li><span><a href="#Filtering-Arrays" data-toc-modified-id="Filtering-Arrays-13"><span class="toc-item-num">13&nbsp;&nbsp;</span>Filtering Arrays</a></span><ul class="toc-item"><li><span><a href="#Creating-the-Filter-Array" data-toc-modified-id="Creating-the-Filter-Array-13.1"><span class="toc-item-num">13.1&nbsp;&nbsp;</span>Creating the Filter Array</a></span></li><li><span><a href="#Creating-Filter-Directly-From-Array" data-toc-modified-id="Creating-Filter-Directly-From-Array-13.2"><span class="toc-item-num">13.2&nbsp;&nbsp;</span>Creating Filter Directly From Array</a></span></li></ul></li><li><span><a href="#Random-Number?" data-toc-modified-id="Random-Number?-14"><span class="toc-item-num">14&nbsp;&nbsp;</span>Random Number?</a></span></li></ul></div>

# What is NumPy?
NumPy is a Python library used for working with arrays.

It also has functions for working in domain of linear algebra, fourier transform, and matrices.

NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.

NumPy stands for Numerical Python.

## Why Use NumPy?
In Python we have lists that serve the purpose of arrays, but they are slow to process.

NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.

The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.

Arrays are very frequently used in data science, where speed and resources are very important.

Data Science: is a branch of computer science where we study how to store, use and analyze data for deriving information from it.

## Why is NumPy Faster Than Lists?
NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.

This behavior is called locality of reference in computer science.

This is the main reason why NumPy is faster than lists. Also it is optimized to work with latest CPU architectures.

## Which Language is NumPy written in?
NumPy is a Python library and is written partially in Python, but most of the parts that require fast computation are written in C or C++.

## Import NumPy


In [2]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)
np.__version__

[1 2 3 4 5]


'1.21.1'

## Create a NumPy ndarray Object
NumPy is used to work with arrays. The array object in NumPy is called ndarray.

We can create a NumPy ndarray object by using the array() function.

type(): This built-in Python function tells us the type of the object passed to it. Like in above code it shows that arr is numpy.ndarray type.



To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray:



In [3]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


## Dimensions in Arrays
A dimension in arrays is one level of array depth (nested arrays).

nested array: are arrays that have arrays as their elements.

## 0-D Arrays
0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.

## Check Number of Dimensions?
NumPy Arrays provides the ndim attribute that returns an integer that tells us how many dimensions the array have.



In [4]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)
print(d)

0
1
2
3
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


## Higher Dimensional Arrays
An array can have any number of dimensions.

When the array is created, you can define the number of dimensions by using the ndmin argument.

In [5]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


# Array Indexing

## Access Array Elements
Array indexing is the same as accessing an array element.

You can access an array element by referring to its index number.

The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc.

In [6]:
arr = np.array([1, 2, 3, 4])

print(arr[2])

3


In [7]:
arr = np.array([1, 2, 3, 4])

print(arr[2] + arr[3])

7


## Access 2-D Arrays
To access elements from 2-D arrays we can use comma separated integers representing the dimension and the index of the element.

In [8]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st dim: ', arr[0, 1])

2nd element on 1st dim:  2


In [9]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('5th element on 2nd dim: ', arr[1, 4])

5th element on 2nd dim:  10


## Access 3-D Arrays
To access elements from 3-D arrays we can use comma separated integers representing the dimensions and the index of the element.


Example Explained

arr[0, 1, 2] prints the value 6.

And this is why:

The first number represents the first dimension, which contains two arrays:

[[1, 2, 3], [4, 5, 6]]

and:

[[7, 8, 9], [10, 11, 12]]

Since we selected 0, we are left with the first array:

[[1, 2, 3], [4, 5, 6]]

The second number represents the second dimension, which also contains two arrays:
[1, 2, 3]

and:

[4, 5, 6]

Since we selected 1, we are left with the second array:

[4, 5, 6]

The third number represents the third dimension, which contains three values:

4

5

6

Since we selected 2, we end up with the third value:

6

In [10]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])

6


## Negative Indexing
Use negative indexing to access an array from the end.

In [11]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


# Array Slicing

Slicing in python means taking elements from one given index to another given index.

We pass slice instead of index like this: [start:end].

We can also define the step, like this: [start:end:step].

If we don't pass start its considered 0

If we don't pass end its considered length of array in that dimension

If we don't pass step its considered 1.

`Note: The result includes the start index, but excludes the end index.`

In [12]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[2:5])
print(arr[4:])
print(arr[:4])

[3 4 5]
[5 6 7]
[1 2 3 4]


## Negative Slicing

Use the minus operator to refer to an index from the end.

## STEP

Use the step value to determine the step of the slicing:

In [13]:
print(arr[-3:-1])

[5 6]


In [14]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])

[2 4]


In [15]:
print(arr[::2])

[1 3 5 7]


## Slicing 2-D Arrays

**Note: Remember that second element has index 1.**

In [16]:
arr = np.array([[1, 2, 3, 4, 5], 
                [6, 7, 8, 9, 10]])

print(arr[1, 1:4])
print(arr[0:2, 2])

# From both elements, slice index 1 to index 4 (not included), 
# this will return a 2-D array:
print(arr[0:2, 1:4]) 

[7 8 9]
[3 8]
[[2 3 4]
 [7 8 9]]


# Data Types

Data Types in Python
By default Python have these data types:

- strings - used to represent text data, the text is given under quote marks. e.g. "ABCD"
- integer - used to represent integer numbers. e.g. -1, -2, -3
- float - used to represent real numbers. e.g. 1.2, 42.42
- boolean - used to represent True or False.
- complex - used to represent complex numbers. e.g. 1.0 + 2.0j, 1.5 + 2.5j

Data Types in NumPy

NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.

Below is a list of all data types in NumPy and the characters used to represent them.

- i - integer
- b - boolean
- u - unsigned integer
- f - float
- c - complex float
- m - timedelta
- M - datetime
- O - object
- S - string
- U - unicode string
- V - fixed chunk of memory for other type ( void )

## Checking the Data Type of an Array
The NumPy array object has a property called dtype that returns the data type of the array:

In [17]:
arr = np.array([1, 2, 3, 4])

print(arr.dtype)

int32


In [18]:
arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)

<U6


In [19]:
arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype) #For i, u, f, S and U we can define size as well.

[b'1' b'2' b'3' b'4']
|S1


In [20]:
arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr)
print(arr.dtype)

[1 2 3 4]
int32


## What if a Value Can Not Be Converted?

If a type is given in which elements can't be casted then NumPy will raise a ValueError.

ValueError: In Python ValueError is raised when the type of passed argument to a function is unexpected/incorrect.

## Converting Data Type on Existing Arrays

The best way to change the data type of an existing array, is to make a copy of the array with the astype() method.

The astype() function creates a copy of the array, and allows you to specify the data type as a parameter.

The data type can be specified using a string, like 'f' for float, 'i' for integer etc. or you can use the data type directly like float for float and int for integer.

In [21]:
arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [22]:
arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype(int)

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [23]:
arr = np.array([1, 0, 3])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

[ True False  True]
bool


# Array Copy vs View

The Difference Between Copy and View
The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.

The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

## COPY:

The copy SHOULD NOT be affected by the changes made to the original array.

In [24]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


## VIEW:

The view SHOULD be affected by the changes made to the original array.

Make Changes in the VIEW:

The original array SHOULD be affected by the changes made to the view.

![](./i/copy_ciew_.png)

![](./i/copy_ciew_modifi.png)

In [25]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [26]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
x[0] = 31

print(arr)
print(x)

[31  2  3  4  5]
[31  2  3  4  5]


## Check if Array Owns it's Data

As mentioned above, copies owns the data, and views does not own the data, but how can we check this?

Every NumPy array has the attribute base that returns None if the array owns the data.

Otherwise, the base  attribute refers to the original object.

**The copy returns None.**

**The view returns the original array.**

In [27]:
arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


# Array Shape

## Shape of an Array
The shape of an array is the number of elements in each dimension.

Get the Shape of an Array
NumPy arrays have an attribute called shape that returns a tuple with each index having the number of corresponding elements.

In [28]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


In [29]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


## What does the shape tuple represent?

Integers at every index tells about the number of elements the corresponding dimension has.


In the example above at index-4 we have value 4, so we can say that 5th ( 4 + 1 th) dimension has 4 elements.

# Reshaping arrays

Reshaping means changing the shape of an array.

The shape of an array is the number of elements in each dimension.

By reshaping we can add or remove dimensions or change number of elements in each dimension.

## Reshape From 1-D to 2-D

In [30]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


## Reshape From 1-D to 3-D

## Can We Reshape Into any Shape?

Yes, as long as the elements required for reshaping are equal in both shapes.


We can reshape an 8 elements 1D array into 4 elements in 2 rows 2D array but we cannot reshape it into a 3 elements 3 rows 2D array as that would require 3x3 = 9 elements.

In [31]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


## Returns Copy or View?


In [32]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

print(arr.reshape(2, 4).base)

[1 2 3 4 5 6 7 8]


The example above returns the original array, so it is a view.

## Unknown Dimension

You are allowed to have one "unknown" dimension.

Meaning that you do not have to specify an exact number for one of the dimensions in the reshape method.

Pass -1 as the value, and NumPy will calculate this number for you.

In [33]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 2, -1)

print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


Note: We can not pass -1 to more than one dimension.

## Flattening the arrays

Flattening array means converting a multidimensional array into a 1D array.

We can use reshape(-1) to do this.

In [34]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)

[1 2 3 4 5 6]


In [35]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr=arr.reshape(1, -1)
newarr

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [36]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr=arr.reshape(-1, 1)
newarr

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

# Iterating Arrays

Iterating means going through elements one by one.

As we deal with multi-dimensional arrays in numpy, we can do this using basic for loop of python.

If we iterate on a 1-D array it will go through each element one by one.

In [37]:
arr = np.array([1, 2, 3])

for x in arr:
    print(x)

1
2
3


## Iterating 2-D Arrays

In a 2-D array it will go through all the rows.

**If we iterate on a n-D array it will go through n-1th dimension one by one.**

In [38]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
    print(x)

[1 2 3]
[4 5 6]


In [39]:
for x in arr:
    for y in x:
        print(y)

1
2
3
4
5
6


## Iterating 3-D Arrays
In a 3-D array it will go through all the 2-D arrays.

In [40]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
    print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [41]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for i in arr:
    for j in i:
        for k in j:
            print(k)

1
2
3
4
5
6
7
8
9
10
11
12


## Iterating Arrays Using nditer()

The function nditer() is a helping function that can be used from very basic to very advanced iterations. It solves some basic issues which we face in iteration, lets go through it with examples.

Iterating on Each Scalar Element
In basic for loops, iterating through each scalar of an array we need to use n for loops which can be difficult to write for arrays with very high dimensionality.

In [42]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


## Iterating Array With Different Data Types

We can use op_dtypes argument and pass it the expected datatype to change the datatype of elements while iterating.

NumPy does not change the data type of the element in-place (where the element is in array) so it needs some other space to perform this action, that extra space is called buffer, and in order to enable it in nditer() we pass flags=['buffered'].

In [43]:
arr = np.array([1, 2, 3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
    print(x)

b'1'
b'2'
b'3'


## Iterating With Different Step Size

We can use filtering and followed by iteration.

In [44]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::2]):
    print(x)

1
3
5
7


## Enumerated Iteration Using ndenumerate()

Enumeration means mentioning sequence number of somethings one by one.

Sometimes we require corresponding index of the element while iterating, the ndenumerate() method can be used for those usecases.

In [45]:
arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
    print(idx, x)

(0,) 1
(1,) 2
(2,) 3


In [46]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr)

print("*************************")

for idx, x in np.ndenumerate(arr):
    print(idx, x)

[[1 2 3 4]
 [5 6 7 8]]
*************************
(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


# Joining NumPy Arrays

Joining means putting contents of two or more arrays in a single array.

In SQL we join tables based on a key, whereas in NumPy we join arrays by axes.

We pass a sequence of arrays that we want to join to the concatenate() function, along with the axis. If axis is not explicitly passed, it is taken as 0.


**Join two 2-D arrays along rows (axis=1)**

In [47]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [48]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


## Joining Arrays Using Stack Functions

Stacking is same as concatenation, the only difference is that stacking is done along a new axis.

We can concatenate two 1-D arrays along the second axis which would result in putting them one over the other, ie. stacking.

We pass a sequence of arrays that we want to join to the stack() method along with the axis. If axis is not explicitly passed it is taken as 0.

In [49]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


## Stacking Along Rows

NumPy provides a helper function: hstack() to stack along rows.

In [50]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


## Stacking Along Columns

NumPy provides a helper function: vstack()  to stack along columns.

In [51]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


## Stacking Along Height (depth)

NumPy provides a helper function: 
    
dstack() to stack along height, which is the same as depth.

In [52]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


# Splitting NumPy Arrays

Splitting is reverse operation of Joining.

Joining merges multiple arrays into one and Splitting breaks one array into multiple.

We use array_split() for splitting arrays, we pass it the array we want to split and the number of splits.

**Note: The return value is an array containing three arrays.**

If the array has less elements than required, it will adjust from the end accordingly.



In [53]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [54]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)

print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


Note: We also have the method split() available but it will not adjust the elements when elements are less in source array for splitting like in example above, array_split() worked properly but split() would fail.

## Split Into Arrays

The return value of the array_split() method is an array containing each of the split as an array.

If you split an array into 3 arrays, you can access them from the result just like any array element:

In [55]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2]
[3 4]
[5 6]


## Splitting 2-D Arrays

Use the same syntax when splitting 2-D arrays.

Use the array_split() method, pass in the array you want to split and the number of splits you want to do.


The example above returns three 2-D arrays.

Let's look at another example, this time each element in the 2-D arrays contains 3 elements.

In [56]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)

newarr

[array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]),
 array([[ 9, 10],
        [11, 12]])]

In [57]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3)

newarr

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [10, 11, 12]]),
 array([[13, 14, 15],
        [16, 17, 18]])]

The example above returns three 2-D arrays.

In addition, you can specify which axis you want to do the split around.

The example below also returns three 2-D arrays, but they are split along the row (axis=1).

In [58]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3, axis=1)

newarr

[array([[ 1],
        [ 4],
        [ 7],
        [10],
        [13],
        [16]]),
 array([[ 2],
        [ 5],
        [ 8],
        [11],
        [14],
        [17]]),
 array([[ 3],
        [ 6],
        [ 9],
        [12],
        [15],
        [18]])]

**An alternate solution is using hsplit() opposite of hstack()**

Note: Similar alternates to vstack() and dstack() are available as vsplit() and dsplit().



In [59]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.hsplit(arr, 3)

newarr

[array([[ 1],
        [ 4],
        [ 7],
        [10],
        [13],
        [16]]),
 array([[ 2],
        [ 5],
        [ 8],
        [11],
        [14],
        [17]]),
 array([[ 3],
        [ 6],
        [ 9],
        [12],
        [15],
        [18]])]

# Searching Arrays

You can search an array for a certain value, and return the indexes that get a match.

To search an array, use the where() method.

In [60]:
arr = np.array([1, 2, 3, 4, 5, 4, 35 , 76 , 96 , 4 , 1, 2, 3, 4,])

x = np.where(arr == 4)

print(x)

(array([ 3,  5,  9, 13], dtype=int64),)


In [61]:

x = np.where(arr%2 == 0)

print(x)

(array([ 1,  3,  5,  7,  8,  9, 11, 13], dtype=int64),)


In [62]:
x = np.where(arr%2 == 1)

print(x)

(array([ 0,  2,  4,  6, 10, 12], dtype=int64),)


## Search Sorted

There is a method called searchsorted() which performs a binary search in the array, and returns the index where the specified value would be inserted to maintain the search order.

The searchsorted() method is assumed to be used on sorted arrays.

In [66]:
arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7)

print(x)

1


Example explained: The number 7 should be inserted on index 1 to remain the sort order.

The method starts the search from the left and returns the first index where the number 7 is no longer larger than the next value.

## Search From the Right Side
By default the left most index is returned, but we can give side='right' to return the right most index instead.

In [68]:
arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7, side='right')

print(x)

2


Example explained: The number 7 should be inserted on index 2 to remain the sort order.

The method starts the search from the right and returns the first index where the number 7 is no longer less than the next value.

## Multiple Values

To search for more than one value, use an array with the specified values.

In [70]:
arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [2, 4, 6])

print(x)

[1 2 3]


# Sorting Arrays

Sorting means putting elements in an ordered sequence.

Ordered sequence is any sequence that has an order corresponding to elements, like numeric or alphabetical, ascending or descending.

The NumPy ndarray object has a function called sort(), that will sort a specified array.

**Note: This method returns a copy of the array, leaving the original array unchanged.**

In [75]:
arr = np.array(['banana', 'cherry', 'apple' , "Xpele" , "Table"])

print(np.sort(arr))

['Table' 'Xpele' 'apple' 'banana' 'cherry']


In [77]:
arr = np.array([True, False, True])

print(np.sort(arr))

[False  True  True]


## Sorting a 2-D Array
If you use the sort() method on a 2-D array, both arrays will be sorted:

In [78]:
arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


# Filtering Arrays
Getting some elements out of an existing array and creating a new array out of them is called filtering.

In NumPy, you filter an array using a boolean index list.

A boolean index list is a list of booleans corresponding to indexes in the array.

If the value at an index is True that element is contained in the filtered array, if the value at that index is False that element is excluded from the filtered array.

In [79]:
arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]

print(newarr)

[41 43]


## Creating the Filter Array
In the example above we hard-coded the True and False values, but the common use is to create a filter array based on conditions.

In [80]:
arr = np.array([41, 42, 43, 44])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is higher than 42, set the value to True, otherwise False:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

    
newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, False, True, True]
[43 44]


In [82]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is completely divisble by 2, set the value to True, otherwise False
  if element % 2 == 0:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, True, False, True, False, True, False]
[2 4 6]


## Creating Filter Directly From Array

The above example is quite a common task in NumPy and NumPy provides a nice way to tackle it.

We can directly substitute the array instead of the iterable variable in our condition and it will work just as we expect it to.

In [83]:
arr = np.array([41, 42, 43, 44])

filter_arr = arr > 42

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False False  True  True]
[43 44]


In [84]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

filter_arr = arr % 2 == 0

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False  True False  True False  True False]
[2 4 6]


# Random Number?

Random number does NOT mean a different number every time. Random means something that can not be predicted logically.

Pseudo Random and True Random.
Computers work on programs, and programs are definitive set of instructions. So it means there must be some algorithm to generate a random number as well.

If there is a program to generate random number it can be predicted, thus it is not truly random.

Random numbers generated through a generation algorithm are called pseudo random.

Can we make truly random numbers?

Yes. In order to generate a truly random number on our computers we need to get the random data from some outside source. This outside source is generally our keystrokes, mouse movements, data on network etc.

We do not need truly random numbers, unless its related to security (e.g. encryption keys) or the basis of application is the randomness (e.g. Digital roulette wheels).

In this tutorial we will be using pseudo random numbers.